
// This file was auto-generated by ML.NET Model Builder. 

using RetentionRateModel_ConsoleApp;

// Create single instance of sample data from first line of dataset for model input
RetentionRateModel.ModelInput sampleData = new RetentionRateModel.ModelInput()
{
    Address = 3F,
    Fund_Source = 2F,
    Fund_Type = 2F,
    HasJob = 0F,
    TotalParentsIncome = 6F,
    NumberOfSiblings = 5F,
    NumberOfDependentSiblings = 14F,
    Strand = 2F,
    JoinedScienceHighSchool = 0F,
    WithHonors = 1F,
    English_Grade_Range = 1F,
    Math_Grade_Range = 7F,
    Science_Grade_Range = 7F,
    GPA = 8F,
    Course = 2F,
    Professor = 1F,
    ModeOfDelivery = 1F,
    HasScholarship = 1F,
    IsInCebu = 1F,
    CurrentStayingPlace = 4F,
    HasEnoughStudySpace = 0F,
    ModeTransportGoingHome = 3F,
    CommuteCountGoingHome = 1F,
    CommuteDurationGoingHome = 2F,
    ModeTransportGoingSchool = 3F,
    CommuteCountGoingSchool = 2F,
    CommuteDurationGoingSchool = 2F,
    HasDevice = 0F,
};

// Make a single prediction on the sample data and print results
var predictionResult = RetentionRateModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual IsShifted with predicted IsShifted from sample data...\n\n");


Console.WriteLine($"Address: {3F}");
Console.WriteLine($"Fund_Source: {2F}");
Console.WriteLine($"Fund_Type: {2F}");
Console.WriteLine($"HasJob: {0F}");
Console.WriteLine($"TotalParentsIncome: {6F}");
Console.WriteLine($"NumberOfSiblings: {5F}");
Console.WriteLine($"NumberOfDependentSiblings: {14F}");
Console.WriteLine($"Strand: {2F}");
Console.WriteLine($"JoinedScienceHighSchool: {0F}");
Console.WriteLine($"WithHonors: {1F}");
Console.WriteLine($"English_Grade_Range: {1F}");
Console.WriteLine($"Math_Grade_Range: {7F}");
Console.WriteLine($"Science_Grade_Range: {7F}");
Console.WriteLine($"GPA: {8F}");
Console.WriteLine($"Course: {2F}");
Console.WriteLine($"Professor: {1F}");
Console.WriteLine($"ModeOfDelivery: {1F}");
Console.WriteLine($"HasScholarship: {1F}");
Console.WriteLine($"IsInCebu: {1F}");
Console.WriteLine($"CurrentStayingPlace: {4F}");
Console.WriteLine($"HasEnoughStudySpace: {0F}");
Console.WriteLine($"ModeTransportGoingHome: {3F}");
Console.WriteLine($"CommuteCountGoingHome: {1F}");
Console.WriteLine($"CommuteDurationGoingHome: {2F}");
Console.WriteLine($"ModeTransportGoingSchool: {3F}");
Console.WriteLine($"CommuteCountGoingSchool: {2F}");
Console.WriteLine($"CommuteDurationGoingSchool: {2F}");
Console.WriteLine($"IsShifted: {0F}");
Console.WriteLine($"HasDevice: {0F}");


Console.WriteLine($"\n\nPredicted IsShifted: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

