Use[StudentDataDB]
GO

INSERT INTO Personal_Info(IdNumber, LastName, FirstName, MiddleName, Address, FundSource, FundSourceType, Job, SalaryEnough, SalaryRange)
VALUES
	('215048994', 'Ong', 'Lovely Shane', 'Pameron', 'Mambaling, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('231987729', 'Cararag', 'Trisha Raye', 'Verano', 'Kimba Cansojong Talisay City Cebu', 'Parents/Guardians', '', '', '', ''),
	('231165150', 'Verdida', 'Fateful', 'Dela Cruz', 'Benison Inn, N. Bacalso Avenue, Cebu City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('236945985', 'JORDAN', 'DANIEL RUSSEL', 'OAKES', 'PAKIGNE, MINGLANILLA, CEBU', 'Parents/Guardians', '', '', '', ''),
	('233109286', 'Cambarihan', 'Archangel', 'Apurado', 'Toledo city', 'Parents/Guardians', '', '', '', ''),
	('170545444', 'Lim', 'Michelu Tia', 'Abello ', '826 Tres de Abril St, Cebu City, 6000 Cebu, Philippines', 'Parents/Guardians', '', '', '', ''),
	('236892742', 'Camay', 'James', 'Palionay', 'Agay-ay St. Poblacion, Liloan, Cebu', 'Parents/Guardians', '', '', '', ''),
	('232648343', 'Lapiña', 'Honey Fate', 'Maisog', 'CASHRA Road, Nivel Hills Lahug C.C.', 'Parents/Guardians', '', '', '', ''),
	('233018809', 'Del Castillo', 'Lilalene', 'Jusay', 'Tres de Abril St. Brgy. Labangon, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('231603575', 'Pacio', 'Muriel', 'Diongzon', 'J. Alcantara Cebu City', 'Parents/Guardians', '', '', '', ''),
	('194004588', 'Idul', 'Carl Kevin', 'Gallardo', 'Liloan', 'Parents/Guardians', '', '', '', ''),
	('232079543', 'Hisoler', 'Rhegynne Leighlane ', 'Monsanto ', '328 Tres de Abril St. Brgy. Punta Princesa, Cebu city ', 'Parents/Guardians', '', '', '', ''),
	('231998921', 'Carcueva', 'Kurt Laurence', 'P.', 'La Aldea Buena Mactan Blk- 8 Lot - 18, Timpolok, Babag 1, Lapu-Lapu City', 'Parents/Guardians', '', '', '', ''),
	('232217877', 'Binagatan', 'Alexander Jr.', 'Bersano', 'Fatima 2nd Street, Brgy. Duljo, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('231754768', 'BASE', 'JASCHA', 'BILLON', 'Sambag Tuyan, City of Naga, Cebu ', 'Parents/Guardians', '', '', '', ''),
	('232772181', 'Acebes', 'Jared Sheohn', 'Legaspi', 'Dr. Pablo U. Abella st., Labangon, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('232753290', 'Espelita', 'Gabriel Lyle', 'Zapanta', 'Cansojong, Talisay City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('231479398', 'Enario', 'Lance Joseph Lorenz', 'Selgas', 'Guadalupe, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233280395', 'Emia', 'Seth Nathaniel', 'Galacio', 'Apt.4, Abella Apt., Dirty St., Labangon., Cebu City', 'Parents/Guardians', '', '', '', ''),
	('232076731', 'DY', 'ZENDY', 'LARA', '237 Agoncillo Street, West Poblacion, City of Naga, Cebu', 'Parents/Guardians', '', '', '', ''),
	('232159735', 'Borgonia', 'John Dymier', 'Osorio', 'Blk 3 Lot 9 South Gate Residences, Paseo Arcenas, Banawa, Cebu City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('201843115', 'Gabutan', 'David', 'Navarce ', 'Guadalupe Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233217874', 'Alvarado', 'Carl Joseph', 'Balabala', 'Block 1 Lot 27 Villa Ventura Subdivision Bag-ong Daan, Yati, Liloan, Cebu', 'Parents/Guardians', '', '', '', ''),
	('232851520', 'Mendoza', 'Mary Grace', 'Langco', 'Ibabao Mambaling Cebu City', 'Parents/Guardians', '', '', '', ''),
	('232297300', 'Casas', 'Elissa Mae', 'Buenvenida ', 'Villa Salud Subd. 1, Good Shepherd Rd. Banawa, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233047534', 'Jacalan', 'Aaron Rey', 'A.', 'Buhisan, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('183084285', 'Layese', 'Hannah Niah', 'Maru', 'Casa Mira Towers Labangon Cebu City', 'Parents/Guardians', '', '', '', ''),
	('232691735', 'Cansico', 'Trisha Mae', 'Capin', 'Sitio Upper Kawayan, B.Rodriguez EXT. Sambag 2, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('236451315', 'Ancheta', 'Kent Vincent', 'Gailanan', 'V. Rama', 'Parents/Guardians', '', '', '', ''),
	('235199828', 'Gimarino', 'Claire Ann', 'Diez', 'Lunas, Asturias, Cebu', 'Parents/Guardians', '', '', '', ''),
	('235762459', 'Casipong', 'Jon Mari', 'Arañas', '2ND Street, Duljo Fatima, Cebu City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('235669609', 'Manigos', 'Charlie', 'Mendez', 'kinasang an pardo ', 'Parents/Guardians', '', '', '', ''),
	('195529442', 'Degamo', 'Kyean Russelle', 'Cervantes', 'Urgello St. Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233917543', 'Kierulf', 'Kelvin Pehrson', 'Ponce', 'Talisay', 'Parents/Guardians', '', '', '', ''),
	('234383545', 'Caralde', 'Jeesandee Joseph', 'Ubanan', 'Punta Princesa, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('215714872', 'Elca', 'Angelo', 'Lico', 'Basak San nicolas', 'Me', 'Private Work', 'Investment', 'Yes', 'greater than 15,000'),
	('234601608', 'Olodin', 'Krizza Beth', 'Martinez', 'Banawa, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233952209', 'Colina', 'Kirsten', 'Maybritt', 'Pasadena St. Vista Grande, Bulacao', 'Parents/Guardians', '', '', '', ''),
	('232416830', 'Arbiol ', 'John Lyster ', 'Tan', 'Maasin City ', 'Parents/Guardians', '', '', '', ''),
	('201140024', 'Erojo', 'Richimir', 'Badilles', 'Brgy. Tisa, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('234184587', 'Cabungcag', 'Vince Astly', 'Nacar', 'Brgy. Bulacao, Talisay City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('130498411', 'LEE', 'KARL JOHN', 'MANTIGUE', 'DONA MARIA VILLAGE 1 CEBU CITY', 'Parents/Guardians', '', '', '', ''),
	('233570713', 'Lomocso', 'Austine John', 'Padro', 'Yati, Liloan, Cebu', 'Parents/Guardians', '', '', '', ''),
	('233389370', 'Tabernero', 'Shervin Dale', 'Maupo', 'Brgy. Guizo Mandaue City', 'Parents/Guardians', '', '', '', ''),
	('233693138', 'Perez', 'John Clyde', 'Jabagat', 'Sambag 1, Urgello, Cebu', 'Parents/Guardians', '', '', '', ''),
	('201140029', 'Plando', 'Kyle', 'Nocos', 'Fatima St, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('225330924', 'Gallardo', 'Eduard Ken ', 'Yso', 'Basak San Nicolas Cebu ', 'Parents/Guardians', '', '', '', ''),
	('234739174', 'Licuanan', 'Kristine Ysabel', 'Ortega', 'J. Urgello St., Sambag 2, Cebu City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('234205826', 'Pinca', 'Jamiel Kyne', 'Rondez', 'Township, Poog, Toledo city', 'Parents/Guardians', '', '', '', ''),
	('234515683', 'Ano-os', 'Iesus Rey', 'Algarme', 'Urban Deca Homes Tisa', 'Parents/Guardians', '', '', '', ''),
	('233429486', 'Arco', 'Joshua', 'D.', 'Naga, tuyan', 'Parents/Guardians', '', '', '', ''),
	('234496954', 'Ewican', 'James', 'Oralde', 'Labangon, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233855504', 'Revelo', 'Camilo Greg', 'Pante', '86A Spolarium Street', 'Parents/Guardians', '', '', '', ''),
	('234078311', 'Morales', 'Dilton Rowan', 'Suico', '-, Greenbelt Drive, Quiot Pardo, Cebu City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('222097673', 'Milleza', 'Jervin Ryle', 'Inoc', '1667, Abuno, Minglanilla, Cebu', 'Parents/Guardians', '', '', '', ''),
	('212600934', 'Doble', 'Reynald Anthony', 'Cuyos', 'Subangdaku, Mandaue City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('213082308', 'Pansacala', 'Jhon Warren', 'Capote', 'Bayabas St. Mambaling, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('211224254', 'Bigno', 'Richemmae', 'Valle', 'Fatima 3rd, Duljo, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('230527402', 'Adolfo', 'Lee Jasmin', 'Ramirez', 'Quiot Pardo, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('231160434', 'Barcelon', 'Jhon Nicole', 'Jabonillo', 'Zone 1 Laguna Street Purol Gumamela Biasong Talisay City', 'Parents/Guardians', '', '', '', ''),
	('234188468', 'Sayson', 'John Michael', 'Robledo', 'Labangon, Cebu, Salvador Street', 'Parents/Guardians', '', '', '', ''),
	('231957693', 'Boniel', 'Symeon Joshua', 'Navales', 'lower tunghaan, minglanilla, cebu', 'Parents/Guardians', '', '', '', ''),
	('231597784', 'Policios', 'Andre', 'Cruz', 'Block 7 Lot 11, Nitrogen St., Phase 3, Deca Homes, Tungkil, Minglanilla, Cebu', 'Parents/Guardians', '', '', '', ''),
	('231648595', 'Sarsonas', 'Kervin Gino', 'Mosquera', 'Maglasang Subd, Labuca street, Cansojong Talisay City, Cebu 6045', 'Me', 'Private Work', 'Assistant Scuba Diver', 'No', 'less than 5,000'),
	('235711257', 'Sultan', 'April John ', 'A.', 'Guibuangan, Barili, Cebu ', 'Parents/Guardians', '', '', '', ''),
	('232290733', 'Habon', 'Michelle Marie', 'Palacio', '60-A Lopez', 'Me', 'Non-Academic Scholars (NAS)', '', '', ''),
	('231982527', 'Laurente', 'Dien Michael ', 'Miao', 'San Nicolas', 'Parents/Guardians', '', '', '', ''),
	('232442334', 'DAAL', 'WYBEN', 'CASQUEJO ', 'Donia Maria Village 1', 'Parents/Guardians', '', '', '', ''),
	('234358139', 'Guadiana', 'Sherielyn', 'Cabugwas', '131-B Cahipa Hipodromo, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('200140043', 'Mendoza', 'Rafael', 'Ababat', '427-O R. Padilla St. Cebu City', 'Parents/Guardians', '', '', '', ''),
	('235102415', 'Diez', 'Mechaela Sofia', 'A.', 'Escala Residence 254-Q, Mercado Compound', 'Parents/Guardians', '', '', '', ''),
	('170338635', 'Archival', 'Shane Nathan', 'Buot', 'Labangon, Tres de Abril', 'Parents/Guardians', '', '', '', ''),
	('120470443', 'Migallos', 'Florence Azriel', 'Roperos', 'N. Bacalso Avenue St. Door B2 Larima ', 'Parents/Guardians', '', '', '', ''),
	('232302526', 'ALORIA', 'SOPHIA BIANCA', 'NA', 'Pinggan, Pakigne, Minglanillia, Cebu', 'Parents/Guardians', '', '', '', ''),
	('231924354', 'SABORNIDO', 'XAVIER JOHN', 'ALCONTIN', 'INAYAWAN, CEBU CITY', 'Parents/Guardians', '', '', '', ''),
	('207429858', 'Ramos', 'Jeremiah', 'Tiston', '91 Visitacion St., Brgy. Sambag II, Cebu City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('232047462', 'Agad', 'Mark laurence', 'Libor', 'Purok Centro 1, Langtad City Of Naga Cebu', 'Parents/Guardians', '', '', '', ''),
	('231805297', 'Vergara', 'Keenan Ravic', 'Aguilar', '0243 F. Ramos St. Cebu City', 'Parents/Guardians', '', '', '', ''),
	('231795734', 'Villas', 'Ervin Louis', 'Bansag', '63-C Cabantan Street, Barangay Luz, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233757111', 'Monteclaro', 'Kurt David', 'Mag-isa', '015-C 3rd Street, Mountain View Village, Quiot, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('235442132', 'Dakay', 'Shanly', 'Lariosa', 'Ward 4 Poblacion Minglanilla Cebu, ', 'Parents/Guardians', '', '', '', ''),
	('235852966', 'Gorre', 'Christian James', 'NA', 'Canduman Mandaue City', 'Parents/Guardians', '', '', '', ''),
	('2017011848', 'Sia', 'David Ryan ', 'Danag', 'Felina Village, Saturn St., Palmero Compound Door 6, Tisa, Cebu', 'Parents/Guardians', '', '', '', ''),
	('235952883', 'Ranido', 'Mitch', 'Apurado', 'mambaling Cebu city', 'Parents/Guardians', '', '', '', ''),
	('231925986', 'ABEL', 'ZYDRIC', 'QUIMBO', '243 MAHAYAHAY A.LOPEZ ST. CALAMBA CEBU CITY ', 'Parents/Guardians', '', '', '', ''),
	('232250144', 'Fernandez', 'Homer', 'Ortega', 'Brgy. Soro-Soro, Maasin City, Southern Leyte', 'Parents/Guardians', '', '', '', ''),
	('231934189', 'Armamento', 'Justin Rey', 'Lariego', 'Purok Lipti, Sitio Acacia, Tungkop, Minglanilla, Cebu, Philippines', 'Parents/Guardians', '', '', '', ''),
	('232256994', 'Quijano', 'Gia Meggie', 'Maaghop', 'V. Rama Ave. Calamba Cebu City, Cebu, Philippines', 'Parents/Guardians', '', '', '', ''),
	('232081111', 'Uy', 'Emman Jay', 'Cañaveral', 'Fatima 4th Street, Duljo-Fatima, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('232426543', 'Rabe', 'Pranz Nicole', 'Cañete', 'Canduman, Mandaue City', 'Parents/Guardians', '', '', '', ''),
	('232082220', 'Mahinay', 'Francis Kyle', 'Gines', 'Brgy. Tungkil Deca Homes, Minglanilla', 'Parents/Guardians', '', '', '', ''),
	('232357568', 'Elorde', 'Earl Jhon Kenneth', 'Sorondo', 'Horizons 101, General Maxilom Avenue, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('230514783', 'Cordero', 'Camila Rose', 'Adlawan', 'Upper Manol, Tisa, Cebu City', 'Me', 'Private Work', 'Social Media Manager', 'Yes', '8,000 to 10,000'),
	('232517769', 'Macopia', 'Gerad Emeka', 'Tamarra', 'Little Baguio II Atillo Rd Punta Princesa Cebu City', 'Parents/Guardians', '', '', '', ''),
	('232013950', 'Lapiz', 'Ailyn', 'Canoy ', 'Lower Kalunasan Cebu City Philippines ', 'Parents/Guardians', '', '', '', ''),
	('231962676', 'Capuras', 'John Miklos', 'Mendez', 'Deca phase 3 Talisay city, Cebu', 'Parents/Guardians', '', '', '', ''),
	('232635609', 'cabahug', 'clarence', 'N\A', 'Tungkil Lipata Minglanilla', 'Parents/Guardians', '', '', '', ''),
	('218410880', 'Taray', 'Julius Andre', 'Mabala', 'Uldog St. Talisay City Cebu', 'Parents/Guardians', '', '', '', ''),
	('230761533', 'Capanpan ', 'Nicolyn ', 'Tampus', 'Tisa deca homes', 'Parents/Guardians', '', '', '', ''),
	('230246135', 'Labaya ', 'Godwin ', 'Monteverde ', 'Sitio. Lomboy, Brngy. Inayawan, Cebu city.', 'Parents/Guardians', '', '', '', ''),
	('232684947', 'ALIGATO', 'ZANDER', 'NAVARRO', 'Tres De Abril, Labangon, Cebu', 'Parents/Guardians', '', '', '', ''),
	('230330749', 'Nuevas', 'Josh Anton', 'Kanen', 'Brgy. Sambag-2 Uytengsu St. West Jones Residences, Cebu City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('230112653', 'Saligue', 'Kean Maverick', 'Wabina', 'Labangon, Mercados Compound', 'Parents/Guardians', '', '', '', ''),
	('230851107', 'Masendo', 'Lyndon', 'V.', 'Labangon', 'Parents/Guardians', '', '', '', ''),
	('231486900', 'Mayuela', 'Judd Kristoffer', 'N/A', 'Poblacion,Talisay City Cebu', 'Parents/Guardians', '', '', '', ''),
	('230267319', 'Pangilinan', 'Vein Carmell', 'Golo', '270 Tres De Abril st. Cebu, City', 'Parents/Guardians', '', '', '', ''),
	('230837809', 'Maldo', 'Nicco Victor', 'Pesa', 'Fuente, Osmena', 'Parents/Guardians', '', '', '', ''),
	('230057927', 'Rellon', 'Elijah Thomas', 'N.', 'Quasi, Tuyom, Carcar City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('230641447', 'Dibdib', 'Wayne Kenji', 'Bajarias ', 'Poblacion Dalaguete Cebu', 'Parents/Guardians', '', '', '', ''),
	('234686868', 'Mantilla', 'Jhondy', 'Dain', 'Mambaling, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('230711470', 'Maestrado', 'Ralph Keane', 'Abaniel ', 'Timpolok, Babag 2, Lapu-Lapu City', 'Parents/Guardians', '', '', '', ''),
	('231151936', 'Larida', 'Mary Maebelle ', 'Alisoso', 'Dumlog, Talisay City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('230866858', 'Jaducana', 'Richelle', 'Bañaga', 'Pob. Talisay, Cebu', 'Parents/Guardians', '', '', '', ''),
	('230716981', 'Coritico', 'Samantha Zhyre', 'Corciega', 'Tres de abril, Labangon, Cebu City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('230706415', 'Yray', 'Philbert', 'n/a', '74 Cabreros St. Basak San Nicolas C.C', 'Parents/Guardians', '', '', '', ''),
	('237074895', 'ANOVA', 'RUBEN CARLO ALESSANDRI', 'MODINA', '456 KATIPUNAN ST LABANGON CEBU CITY 6000', 'Parents/Guardians', '', '', '', ''),
	('230100845', 'CAUBAN', 'JOHN ANDREW', 'JUANICO', 'Mercados Compound Tres de Abril', 'Parents/Guardians', '', '', '', ''),
	('231009711', 'Macansantos', 'Axcelson', 'Odchigue', 'Bag-ong dan, Yati, Lilo-an, Cebu', 'Parents/Guardians', '', '', '', ''),
	('230695527', 'Ruperez ', 'Raymart ', 'Naparate', 'Sector 6, barangay pagsabungan mandaue city ', 'Parents/Guardians', '', '', '', ''),
	('231213960', 'URSULO', 'LICHAEL YASHUA', 'ESCALA', '78 F Pacana Street Labangon', 'Parents/Guardians', '', '', '', ''),
	('231010477', 'Banico', 'Joseph James', 'Tabanao', 'Jugan, Consolacion, Cebu', 'Parents/Guardians', '', '', '', ''),
	('230076146', 'Buot', 'Leslee Jezzel', 'Largo', '73 sitio lower san roque, bulacao cebu city', 'Parents/Guardians', '', '', '', ''),
	('230529787', 'Benolirao ', 'Clyde ', 'Cabaluna ', 'Guiwang Alcoy Cebu ', 'Parents/Guardians', '', '', '', ''),
	('230185503', 'Cahiyang', 'Gabriel', 'Barquio', 'Cebu, Brgy Labangon, Sabina dormitory', 'Parents/Guardians', '', '', '', ''),
	('231315571', 'Cabasag', 'Ma. Melessa', 'Villas', 'Obong, Dalaguete', 'Parents/Guardians', '', '', '', ''),
	('230225681', 'Caones', 'Lerah', 'Arpon', 'Poblacion Pardo Cebu City', 'Parents/Guardians', '', '', '', ''),
	('230345916', 'LIBATO', 'MICHAEL GRANT', 'SALDON', 'Lomboy Banawa, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('230952972', 'Salonga', 'Andre', 'Devero', 'Helenville Subd., Mactan, Lapu-Lapu City', 'Parents/Guardians', '', '', '', ''),
	('230197396', 'Gaviola', 'John Michael ', 'Rosellosa', 'Labangon', 'Parents/Guardians', '', '', '', ''),
	('231121678', 'Apor', 'Ken Ferry Louie', 'Avenido', 'Paknaan Mandaue City', 'Parents/Guardians', '', '', '', ''),
	('201040027', 'Abadinas', 'Treasure Louise ', 'Soberano', 'Aznar Rd., Tangkongan, Sambag I, Cebu City ', 'Parents/Guardians', '', '', '', ''),
	('231156855', 'Alia', 'Myron Deandre', 'Gallardo', 'Labangon, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233773764', 'Barcenas', 'Jon Vic', 'Torres', 'Labangon, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('230209694', 'DABALOS', 'ERICA', 'Y.', 'Mohon, Tutay, Pinamungajan, Cebu', 'Parents/Guardians', '', '', '', ''),
	('207631433', 'Cenas', 'Cassius', 'Layan', 'Lawaan 3 talisay city cebu ', 'Me', 'Private Work', 'Online reseller', 'No', 'less than 5,000'),
	('231889639', 'Dabon', 'Kenn Xavier', 'Cabonilas', 'Purok Onion 2, Oceanside Village South Poblacion, City of Naga, Cebu', 'Parents/Guardians', '', '', '', ''),
	('230801572', 'IGONIA', 'ASHLEY', '-', 'F. Jaca St., Inayawan, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('236163279', 'Bigtasin', 'Van Andrae', 'Palmares', 'Cantabaco, Toledo City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('236693453', 'Riambon', 'Regy', 'Catay', 'punta princesa', 'Parents/Guardians', '', '', '', ''),
	('233529427', 'Larita', 'Franzlee', 'Monreal', 'St. Mary’s Heights Linao Talisay City Cebu', 'Parents/Guardians', '', '', '', ''),
	('236345966', 'Baril', 'Joygen', 'Bantay', 'Lower Gochan Quiot Cebu City', 'Parents/Guardians', '', '', '', ''),
	('236684160', 'Amoguis', 'Philma Jenica', 'Bustamante', 'Urgello Street, Sambag 1, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('236492687', 'Bebita', 'Kent Michael', 'Estrella', '16-A Andres Abellana St . Guadalupe Cebu City', 'Parents/Guardians', '', '', '', ''),
	('230148359', 'Tabanas', 'Prince Daniel', 'Rejano', 'Pandayan Sanchez Compound, Basak San Nicholas, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('236786523', 'Delos Reyes', 'Karl Christian', 'Oralde', 'Banawa', 'Parents/Guardians', '', '', '', ''),
	('232220418', 'Soco', 'Kurt ', 'Kabalican', '968-D V.Rama Avenue', 'Parents/Guardians', '', '', '', ''),
	('236379922', 'Baculi', 'Mieann', 'Malaga ', '8a jade st. sta tereseta village tisa cebu city', 'Parents/Guardians', '', '', '', ''),
	('213398579', 'Briz', 'Danniel Roque', 'Tuñacao', 'Minglanillia, Deca Homes Phase 1, Block 9 Lot 46', 'Parents/Guardians', '', '', '', ''),
	('236061203', 'Baul', ' Elan Sheremak', 'Dael', '241 Maralag, Manipis, Tanjay City, Negros Oriental', 'Parents/Guardians', '', '', '', ''),
	('234200947', 'SOTEN', 'EMELHIE', 'YFANTO', 'N. Bacalso Ave. Mambaling, Cebu, City', 'Parents/Guardians', '', '', '', ''),
	('236700709', 'Najarro', 'Monica', 'Ancajas', '101 Alumnos Basak San Nicolas Cebu City', 'Parents/Guardians', '', '', '', ''),
	('236586877', 'Francisco', 'Shalaica ', 'Vargas', 'Mingcourt village bulacao talisay city cebu', 'Parents/Guardians', '', '', '', ''),
	('236808546', 'Rubio', 'Jecie Jade', 'B.', '1567, Dawis Rd, Tabunok, Talisay City', 'Parents/Guardians', '', '', '', ''),
	('201477175', 'Geraldez', 'Junjie', 'Lapiz', 'Colon, City of Naga, Cebu', 'Parents/Guardians', '', '', '', ''),
	('236845234', 'Matsuda', 'Joji', 'Oliverio', 'Door D2 Ong Compound Sacred Heart Village M. Salvador Ext. Brgy. Labangon, Cebu City 6000', 'Parents/Guardians', '', '', '', ''),
	('236835448', 'Ballener', 'John Mark', 'Delalamon', 'Tuanson Apartment Door 6, Laray San Roque, Talisay City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('170726103', 'Amad', 'Karylle', 'V.', 'karylleamad1@gmail.com', 'Me', 'Private Work', 'Online stuffs but it ended already so basically this is just my savings.', 'No', 'less than 5,000'),
	('233308981', 'Justimbaste', 'Josh', 'Golez', 'La Familia Village, Tugas Pardo, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('201140035', 'Abelgas ', 'Francis Carl', 'Dumagan', '187 Ubca 3 Quiot Cebu City', 'Parents/Guardians', '', '', '', ''),
	('214285868', 'Castillo', 'Teodoro Jr.', 'Dinoy', 'Kalunasan, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233163213', 'Secong', 'Marc Benn', 'Bagoyado', '42-B Stockton Village, Punta Princesa, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('232958771', 'Lagamo', 'Elvin', 'Opalla', 'Dait Norte, Buenavista, Bohol', 'Parents/Guardians', '', '', '', ''),
	('212663704', 'Capadngan', 'Bryan Kim', 'Vidad', '116 Salvador Ext. Labangon Cebu City ', 'Me', 'Private Work', 'BPO/ Call Center agent ', 'No', '10,000 to 15,000'),
	('236562740', 'Ceballos', 'Johnlex', 'Gonzaga', 'Sitio nalsubi labangon cebu city', 'Parents/Guardians', '', '', '', ''),
	('230170798', 'Loy', 'Andrei Sam', 'Planco', 'Duljo, Fatima', 'Parents/Guardians', '', '', '', ''),
	('211874319', 'Bullo', 'Christian Dave', 'Mayol', 'Lawaan, Talisay City, Cebu', 'Parents/Guardians', '', '', '', ''),
	('234803498', 'Azcuna', 'Christian Joel', 'De Llanderal', 'Gorordo Ave, Cebu City, 6000 Cebu 14D', 'Parents/Guardians', '', '', '', ''),
	('233174814', 'Estrera', 'Michaela Ma. Alexa', 'Densing', '464 Cabarrubias Compound, Tisa, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('237098245', 'Maquiling', 'Mary Grace', 'Gorrero', '43 Calle Rojo, Lahug, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('232708807', 'Mendez', 'Edichar', 'Abreu', 'Minglanilla Cebu, tungkil', 'Parents/Guardians', '', '', '', ''),
	('213920383', 'Sevilla', 'John Emmanuel', 'S.', 'Alaska Mambaling, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('233045817', 'Ogang', 'Jorge Martin ', 'Matiga', 'Phase 1 blck 28, lot 24, Deca homes, Dumlog, Talisay city, Cebu', 'Parents/Guardians', '', '', '', ''),
	('233030981', 'Cortes', 'Isaac Raphael ', 'P.', 'Cebu, Talisay City, Pooc, Puerto Del Sol sub', 'Parents/Guardians', '', '', '', ''),
	('233422570', 'Pacaña', 'Clint', 'n/a', '1038 bontores street basak san nicolas cebu city', 'Parents/Guardians', '', '', '', ''),
	('170440799', 'Catamco', 'Danise Bianca', 'Bulado', 'Quiot, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('170945255', 'Daclan', 'Rusty Summer', '-', '42 B Salvador st. Labangon C.C', 'Parents/Guardians', '', '', '', ''),
	('201140187', 'Galo', 'Margel Destine Krizia ', 'Flaviano', '739-B Tres de Abril St., Labangon, Cebu City', 'Parents/Guardians', '', '', '', ''),
	('232073528', 'Lao', 'Hilary Danne', 'Chapa', '4th street Carmen village poblacion talisay', 'Parents/Guardians', '', '', '', ''),
	('231302875', 'Dela Cruz', 'Rohana Jane', 'Emit', '239-i Elizabethpond Extension C.C', 'Parents/Guardians', '', '', '', ''),
	('235403973', 'DIALIMAS ', 'NIRHVEN KYLE ', 'CABABAT ', 'Guiwang Alcoy Cebu ', 'Parents/Guardians', '', '', '', ''),
	('231018639', 'Cortado', 'Reynan', 'Sapilan', 'DAS OCYOU, Toledo City', 'Parents/Guardians', '', '', '', '');